// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb78KlU5IY1cyWa45n7v-9EMrjCzr6QIw',
    appId: '1:971389332951:web:54e5304423ac72a197af92',
    messagingSenderId: '971389332951',
    projectId: 'flutterfinals',
    authDomain: 'flutterfinals.firebaseapp.com',
    storageBucket: 'flutterfinals.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiWXV6o0ApOMiTdgI_h0C2O5FG1B3h3ws',
    appId: '1:971389332951:android:79a1df097a82f55c97af92',
    messagingSenderId: '971389332951',
    projectId: 'flutterfinals',
    storageBucket: 'flutterfinals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTG4REEOGzKDc_m7yzpsUoNqx8rQX1yhU',
    appId: '1:971389332951:ios:adeada3a2b7b325a97af92',
    messagingSenderId: '971389332951',
    projectId: 'flutterfinals',
    storageBucket: 'flutterfinals.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTG4REEOGzKDc_m7yzpsUoNqx8rQX1yhU',
    appId: '1:971389332951:ios:90a80b8f1472de8397af92',
    messagingSenderId: '971389332951',
    projectId: 'flutterfinals',
    storageBucket: 'flutterfinals.appspot.com',
    iosBundleId: 'com.example.finalproject.RunnerTests',
  );
}
